//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"os"
	"strconv"
)

func main() {
	for _, schema := range []struct {
		input, output, constant string
	}{
		{input: "../../schema/modules.schema.json", output: "modules_schema_generated.go", constant: "modulesSchemaJSON"},
		{input: "../../schema/cohesion-catalog.schema.json", output: "catalog_schema_generated.go", constant: "catalogSchemaJSON"},
		{input: "../../schema/cohesion-inputs.schema.json", output: "inputs_schema_generated.go", constant: "inputsSchemaJSON"},
		{input: "../../schema/cohesion-sources.schema.json", output: "sources_schema_generated.go", constant: "sourcesSchemaJSON"},
	} {
		data, err := os.ReadFile(schema.input)
		if err != nil {
			panic(err)
		}
		source := "// Code generated by go generate; DO NOT EDIT.\n" +
			"package cohesion\n\n" +
			"const " + schema.constant + " = " + strconv.Quote(string(data)) + "\n"
		if schema.constant == "modulesSchemaJSON" {
			source = "// Code generated by go generate; DO NOT EDIT.\n" +
				"//go:generate go run schema_generate_main.go\n\n" +
				"package cohesion\n\n" +
				"const " + schema.constant + " = " + strconv.Quote(string(data)) + "\n"
		}
		formatted, err := format.Source([]byte(source))
		if err != nil {
			panic(fmt.Errorf("format embedded schema: %w", err))
		}
		if err := os.WriteFile(schema.output, formatted, 0o600); err != nil {
			panic(err)
		}
	}
}
