//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"os"
	"strconv"
)

func main() {
	data, err := os.ReadFile("../../schema/modules.schema.json")
	if err != nil {
		panic(err)
	}
	source := "// Code generated by go generate; DO NOT EDIT.\n" +
		"//go:generate go run schema_generate_main.go\n\n" +
		"package cohesion\n\n" +
		"const modulesSchemaJSON = " + strconv.Quote(string(data)) + "\n"
	formatted, err := format.Source([]byte(source))
	if err != nil {
		panic(fmt.Errorf("format embedded schema: %w", err))
	}
	if err := os.WriteFile("modules_schema_generated.go", formatted, 0o600); err != nil {
		panic(err)
	}
}
