//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"os"
	"strconv"
)

func main() {
	for _, schema := range []struct {
		input, output, constant string
	}{
		{input: "../../schema/modules.schema.json", output: "modules_schema_generated.go", constant: "modulesSchemaJSON"},
		{input: "../../schema/cohesion-catalog.schema.json", output: "catalog_schema_generated.go", constant: "catalogSchemaJSON"},
		{input: "../../schema/cohesion-inputs.schema.json", output: "inputs_schema_generated.go", constant: "inputsSchemaJSON"},
		{input: "../../schema/cohesion-sources.schema.json", output: "sources_schema_generated.go", constant: "sourcesSchemaJSON"},
		{input: "../../schema/cohesion-contract-review-v1.schema.json", output: "contract_review_v1_schema_generated.go", constant: "contractReviewV1SchemaJSON"},
		{input: "../../schema/cohesion-contract-freeze-v1.schema.json", output: "contract_freeze_v1_schema_generated.go", constant: "contractFreezeV1SchemaJSON"},
		{input: "../../schema/cohesion-schema-v3-decision-review-v1.schema.json", output: "schema_v3_decision_review_v1_schema_generated.go", constant: "schemaV3DecisionReviewV1SchemaJSON"},
		{input: "../../schema/cohesion-schema-v3-decision-freeze-v1.schema.json", output: "schema_v3_decision_freeze_v1_schema_generated.go", constant: "schemaV3DecisionFreezeV1SchemaJSON"},
		{input: "../../schema/modules-v1.schema.json", output: "modules_v1_schema_generated.go", constant: "modulesV1SchemaJSON"},
		{input: "../../schema/modules-v2.schema.json", output: "modules_v2_schema_generated.go", constant: "modulesV2SchemaJSON"},
		{input: "../../schema/modules-v3.schema.json", output: "modules_v3_schema_generated.go", constant: "modulesV3SchemaJSON"},
		{input: "../../schema/cohesion-catalog-v1.schema.json", output: "catalog_v1_schema_generated.go", constant: "catalogV1SchemaJSON"},
		{input: "../../schema/cohesion-catalog-v2.schema.json", output: "catalog_v2_schema_generated.go", constant: "catalogV2SchemaJSON"},
		{input: "../../schema/cohesion-inputs-v1.schema.json", output: "inputs_v1_schema_generated.go", constant: "inputsV1SchemaJSON"},
		{input: "../../schema/cohesion-inputs-v2.schema.json", output: "inputs_v2_schema_generated.go", constant: "inputsV2SchemaJSON"},
		{input: "../../schema/cohesion-sources-v1.schema.json", output: "sources_v1_schema_generated.go", constant: "sourcesV1SchemaJSON"},
		{input: "../../schema/cohesion-sources-v2.schema.json", output: "sources_v2_schema_generated.go", constant: "sourcesV2SchemaJSON"},
		{input: "../../schema/cohesion-delivery-evidence-v1.schema.json", output: "delivery_evidence_v1_schema_generated.go", constant: "deliveryEvidenceV1SchemaJSON"},
		{input: "../../schema/cohesion-authorization-registry-v1.schema.json", output: "authorization_registry_v1_schema_generated.go", constant: "authorizationRegistryV1SchemaJSON"},
		{input: "../../schema/cohesion-authorization-record-v1.schema.json", output: "authorization_record_v1_schema_generated.go", constant: "authorizationRecordV1SchemaJSON"},
		{input: "../../schema/cohesion-residual-inventory-v1.schema.json", output: "residual_inventory_v1_schema_generated.go", constant: "residualInventoryV1SchemaJSON"},
		{input: "../../schema/cohesion-residual-register-v1.schema.json", output: "residual_register_v1_schema_generated.go", constant: "residualRegisterV1SchemaJSON"},
		{input: "../../schema/cohesion-gate-policy-v1.schema.json", output: "gate_policy_v1_schema_generated.go", constant: "gatePolicyV1SchemaJSON"},
		{input: "../../schema/cohesion-go-toolchains-v1.schema.json", output: "go_toolchains_v1_schema_generated.go", constant: "goToolchainsV1SchemaJSON"},
		{input: "../../schema/cohesion-go-official-downloads-oracle-v1.schema.json", output: "go_official_downloads_oracle_v1_schema_generated.go", constant: "goOfficialDownloadsOracleV1SchemaJSON"},
		{input: "../../schema/cohesion-go-official-downloads-oracle-review-v1.schema.json", output: "go_official_downloads_oracle_review_v1_schema_generated.go", constant: "goOfficialDownloadsOracleReviewV1SchemaJSON"},
		{input: "../../schema/cohesion-engineering-identities-v1.schema.json", output: "engineering_identities_v1_schema_generated.go", constant: "engineeringIdentitiesV1SchemaJSON"},
		{input: "../../schema/cohesion-schema-provenance-v1.schema.json", output: "schema_provenance_v1_schema_generated.go", constant: "schemaProvenanceV1SchemaJSON"},
		{input: "../../schema/cohesion-schema-provenance-v2.schema.json", output: "schema_provenance_v2_schema_generated.go", constant: "schemaProvenanceV2SchemaJSON"},
		{input: "../../schema/cohesion-diagnostic-v1.schema.json", output: "diagnostic_v1_schema_generated.go", constant: "diagnosticV1SchemaJSON"},
	} {
		data, err := os.ReadFile(schema.input)
		if err != nil {
			panic(err)
		}
		source := "// Code generated by go generate; DO NOT EDIT.\n" +
			"package cohesion\n\n" +
			"const " + schema.constant + " = " + strconv.Quote(string(data)) + "\n"
		if schema.constant == "modulesSchemaJSON" {
			source = "// Code generated by go generate; DO NOT EDIT.\n" +
				"//go:generate go run schema_generate_main.go\n\n" +
				"package cohesion\n\n" +
				"const " + schema.constant + " = " + strconv.Quote(string(data)) + "\n"
		}
		formatted, err := format.Source([]byte(source))
		if err != nil {
			panic(fmt.Errorf("format embedded schema: %w", err))
		}
		if err := os.WriteFile(schema.output, formatted, 0o600); err != nil {
			panic(err)
		}
	}
}
