// Command genschemas embeds the published security-record schemas in the validator.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

func main() {
	var output bytes.Buffer
	_, _ = fmt.Fprintln(&output, "// Code generated by go generate; DO NOT EDIT.")
	_, _ = fmt.Fprintln(&output, "package securitydocs")
	for _, source := range []struct{ name, constant string }{
		{"security-risk-register.schema.json", "riskRegisterSchema"},
		{"security-matrix.schema.json", "securityMatrixSchema"},
	} {
		data, err := os.ReadFile(filepath.Join("..", "..", "schema", source.name))
		if err != nil {
			panic(err)
		}
		_, _ = fmt.Fprintf(&output, "\nconst %s = %q\n", source.constant, string(data))
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(err)
	}
	// #nosec G306 -- generated Go source is a tracked repository file and must remain world-readable
	if err := os.WriteFile("security_schemas_generated.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
