//go:build ignore

package main

import (
	"fmt"
	"os"
	"strconv"
)

func main() {
	base, err := os.ReadFile("../../schema/modules.schema.json")
	if err != nil {
		panic(err)
	}
	v3, err := os.ReadFile("../../schema/modules-v3.schema.json")
	if err != nil {
		panic(err)
	}
	source := fmt.Sprintf("// Code generated by go generate; DO NOT EDIT.\n\npackage inventory\n\nconst modulesSchemaJSON = %s\nconst modulesV3SchemaJSON = %s\n", strconv.Quote(string(base)), strconv.Quote(string(v3)))
	if err := os.WriteFile("schema_generated.go", []byte(source), 0o600); err != nil {
		panic(err)
	}
}
