package inventory_test

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"testing"
	"time"
)

func TestSchemaGeneratorProducesBothSchemasSuccessfully(t *testing.T) {
	root := t.TempDir()
	working := filepath.Join(root, "internal", "inventory")
	for _, directory := range []string{working, filepath.Join(root, "schema"), filepath.Join(root, "cache"), filepath.Join(root, "modules"), filepath.Join(root, "tmp")} {
		if err := os.MkdirAll(directory, 0o700); err != nil {
			t.Fatal(err)
		}
	}
	source, err := os.ReadFile("schema_generate_main.go")
	if err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(working, "schema_generate_main.go"), string(source))
	schemas := make([]string, 0, 2)
	for _, name := range []string{"modules.schema.json", "modules-v3.schema.json"} {
		content, err := os.ReadFile(filepath.Join("..", "..", "schema", name))
		if err != nil {
			t.Fatal(err)
		}
		schemas = append(schemas, string(content))
		write(t, filepath.Join(root, "schema", name), string(content))
	}
	ctx, cancel := context.WithTimeout(t.Context(), time.Minute)
	defer cancel()
	command := exec.CommandContext(ctx, "go", "run", "schema_generate_main.go")
	command.Dir = working
	command.Env = append(os.Environ(),
		"GOWORK=off", "GOTOOLCHAIN=local",
		"GOCACHE="+filepath.Join(root, "cache"),
		"GOMODCACHE="+filepath.Join(root, "modules"),
		"GOTMPDIR="+filepath.Join(root, "tmp"),
	)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("schema generator must exit successfully: %v, context=%v, output=%s", err, ctx.Err(), output)
	}
	generated, err := os.ReadFile(filepath.Join(working, "schema_generated.go"))
	if err != nil {
		t.Fatal(err)
	}
	want := fmt.Sprintf("// Code generated by go generate; DO NOT EDIT.\n\npackage inventory\n\nconst modulesSchemaJSON = %s\nconst modulesV3SchemaJSON = %s\n", strconv.Quote(schemas[0]), strconv.Quote(schemas[1]))
	if string(generated) != want {
		t.Fatal("schema generator did not preserve both exact schema inputs")
	}
}
